# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6ba76b20-2b21-4643-afac-6e1b3356b4c4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6ba76b20-2b21-4643-afac-6e1b3356b4c4".device = "/dev/disk/by-uuid/6ba76b20-2b21-4643-afac-6e1b3356b4c4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3392-9ACB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-17e384af-0628-410e-a8f2-f43a9e2ab5ae"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
